### ISSUE TITLE
'OptDMD.predict' does not work with default argument `factorization='evd'`

### ISSUE THREAD

**Issue by ConstantinGahr** [mathLab/PyDMD#226]
If I run `OptDMD` with default argument `factorization='evd'`, the error `'OptDMD' object has no attribute '_eigs'` is raised. This is an easy fix, replace `self._eigs` with `self.eigs`. However, doing so introduces a new bug.

Running `OptDMD` with `factorization='svd'` works fine.

**Describe the bug**
Simply running `OptDMD.fit` and `OptDMD.predcit` causes an exception.

**To Reproduce**
fit `OptDMD` and try to predict (with default arguments and rank=7)

**Expected behavior**
There shouldn't be an exception.

**Output**
```python
Traceback (most recent call last):
  ...
  File "/home/user/anaconda3/envs/test/lib/python3.9/site-packages/pydmd/optdmd.py", line 235, in predict
    Y = np.linalg.multi_dot(
  File "<__array_function__ internals>", line 5, in multi_dot
  File "/home/user/anaconda3/envs/test/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 2724, in multi_dot
    _assert_2d(*arrays)
  File "/home/user/anaconda3/envs/test/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 190, in _assert_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 1-dimensional array given. Array must be two-dimensional
```

**Additional context**
I looked into what causes this bug and there seems to be a mismatch in dimensions:
```python
Y = np.linalg.multi_dot(
    [
        self._output_space,
        np.diag(self.eigs),
        self._input_space.T.conj(),
        X,
    ]
)
```
We have the following shapes:
```python
self._output_space.shape = (128, 7)
np.diag(self.eigs).shape = (7, 7)
self._input_space.T.conj().shape = (7, )
X.shape = (128, )
```
This does not match. My best guess is, that the shape of the third matrix should be `self._input_space.shape == (128, 7)` so that the result after the multiplication has a shape of `(128, )`.

**Comment by TJ-coding** [comment]
I believe this bug is a result of someone mistaking thinking `self.eig` returns Eigen vectors when it returns Eigen values.
``` python
elif self.factorization == "evd":
    # --> Compute DMD eigenvalues and right/left eigenvectors
    self._input_space = self.eigs
    self._output_space = self.operator.right_eigenvectors
```
I changed the above to:
``` python
  elif self.factorization == "evd":
      # --> Compute DMD eigenvalues and right/left eigenvectors
      self._input_space = self.operator._eigenvectors
      self._output_space = self.operator.right_eigenvectors
```
